### ISSUE TITLE
[Bug] Can not use side bar to preview equation after switch back to source code mode.

### ISSUE THREAD

**Issue by PeterWang-dev** [quarto-dev/quarto#141]
1. Write markdown mathjax  in a list (list block) in source code mode and math preview bahaves well.
2. Switch to visual mode and edit something.
3. Switch back to source code mode from visual mode and then the markdown codes are re-fomated.
4. Math preview can not render the mathjax in list blocks.

That is due to the indent. Before changing to visual mode, I use only one space after list index and following blocks are aligned to the first character after the index. 

For example,

```markdown
1. $\text{first mathjax}$

   $$
   \text{block mathjax}
   $$
```

This works well. But after editing in visual mode, indent has been changed.

```markdown
1.  $\text{two spaces before math}$

    $$
    \text{four spaces before math}
    $$
```

Putting the cursor between the math deliminator, the preview in the side bar cannot render math in list and list block.

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here: https://github.com/quarto-dev/quarto/commit/121dc72195294f26124a888b35b4ac8ac0397b39

**Comment by PeterWang-dev** [comment]
The issue still exists.

```markdown
2.  xxxxx:

    xxxxxxxxxxxx：

    $$
    \left[
    \begin{matrix}
      2.51 & 1.48 & 4.53 & 0.05 \\
      1.48 & 0.93 & -1.3 & 1.03 \\
      2.68 & 3.04 & -1.48 & -0.53
    \end{matrix}
    \right]
    $$
```

The matrix here cannot be render in side bar.

**Comment by jjallaire** [comment]
It looks like we weren't handling lists with > 2 blocks correctly. Fix is here: https://github.com/quarto-dev/quarto/commit/09e086e7ecf65a4e1f137abfd1caa68d2cac9054 (will be in next release)

**Comment by PeterWang-dev** [comment]
> It looks like we weren't handling lists with > 2 blocks correctly. Fix is here: [09e086e](https://github.com/quarto-dev/quarto/commit/09e086e7ecf65a4e1f137abfd1caa68d2cac9054) (will be in next release)

Thank you for your quick fix and great contribution! :)
